volumes:
  pg_data:
  backend_static:
  frontend_build:
  media:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: daniilpletnev/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static/
      - media:/app/media/
    command: sh -c "python manage.py collectstatic --noinput && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: daniilpletnev/foodgram_frontend:latest
    container_name: frontend
    restart: always
    volumes:
      - frontend_build:/usr/share/nginx/html
    command: >
      sh -c "
      rm -rf /usr/share/nginx/html && 
      cp -r /app/build /usr/share/nginx/html &&
      echo 'Статика фронтенда скопирована' &&
      tail -f /dev/null
      "

  gateway:
    image: daniilpletnev/foodgram_gateway:latest
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - frontend_build:/usr/share/nginx/html
      - backend_static:/app/static
      - media:/app/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend