volumes:
  pg_data:
  backend_static:
  frontend_static:
  media:
  
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: daniilpletnev/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static/
      - media:/app/media/

  frontend:
    image: daniilpletnev/foodgram_frontend:latest
    volumes:
      - frontend_static:/frontend_static/
    command: sh -c "cp -r /app/build/. /frontend_static/ && python manage.py collectstatic --noinput"
    depends_on:
      - backend

  gateway:
    image: daniilpletnev/foodgram_gateway:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - frontend_static:/frontend_static
      - backend_static:/app/static 
      - ./media:/app/media
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend