USERNAME_LENGTH = 150
FIRST_NAME_LENGTH = 150
LAST_NAME_LENGTH = 150
EMAIL_LENGTH = 254

TAG_NAME_LENGTH = 32
TAG_SLUG_LENGTH = 32

INGREDIENT_NAME_LENGTH = 150
INGREDIENT_MEASUREMENT_UNIT_LENGTH = 50

RECIPE_NAME_LENGTH = 256
MIN_COOKING_TIME_VALUE = 1
MAX_COOKING_TIME_VALUE = 1440
MIN_AMOUNT_INGREDIENT = 1
